language: python
python:
- '3.5'
install: make install
script: make test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: rE8cZHdVr2ybXjXuoLoRTHMSsIg7fg8FP2Z8YWQR7wQtZmOkyAhvAotTrtIbqdPVEoxNOFG+yVSONX/h232RK/7EBCRP3fwAYAmGeukO/wyMYpY7kZBdq+EymJyRl2WdeOTPSNPe5EqDYoGqNfmJI1i4pF3vAEFzezylOI3yidS0w6l201XJLdAqVjA51yqkEoHpCoTy0w66vEHMsZzp07euFvWb0iC+/NuiePGJ0o+UJH835pScRguN+pk7KyZ1UMqRjx/wa3spXvPNCF1x435NSE81gP/P4fF3YZf2yo8WLElScYa9uzVh+z4uRg4DWnWjE1OSSFx+613szOi/Ghw5+9j27z+atI1YAWcdDyS+Y/iXLdMn/z0UQSLYyXej7+3wWC4hyXEmXjUpfFigXl93tP4GqxVeekg3xbnq+ypjCw/ypqrFh0wWtDdyoqx0T3xyRjzCzOzOfn/NVxTtBPd6GTl80dJ8ljLuv2nRzPDKOUcy9BZ1ENukMTkSJBNw45Za0i69++IXms6iJsNcLU2vz+p8ElCFW1j3N5xBMFovR3hdxurwPknO4cz883OIFohmltydF5w3wOT2cjg3fMNuwXTJk9TgUn6408Po8b417HkKEsDTv7wLevKyU0Q1JILCzs+RK2eLMXr3mBSdm1b06pR1b4khq/gtZ7p61KM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/protowhat
  skip_upload_docs: true
